/// The Hinglish "kaun sabse zyada…" deck. Phrased as questions because that
/// is how the game is actually shouted across a room.
const kMostLikelyToPromptsHinglish = <String>[
  'Kaun sabse pehle famous hoga?',
  'Kaun apna hi birthday bhool jaayega?',
  'Kaun zombie apocalypse mein sabse aakhir tak bachega?',
  'Kaun shaadi mein sabse zyada royega?',
  'Kaun Google Maps hote hue bhi raasta bhatak jaayega?',
  'Kaun lottery jeet ke ticket kho dega?',
  'Kaun police wale se baat karke challan bachwa lega?',
  'Kaun party mein sabse pehle so jaayega?',
  'Kaun bina soche samjhe startup shuru kar dega?',
  'Kaun ghar mein paanch kutte paal lega?',
  'Kaun sabse pehle crorepati banega?',
  'Kaun videsh jaake settle ho jaayega?',
  'Kaun apna joke poora hone se pehle hi hasne lagega?',
  'Kaun teen din baad reply karega?',
  'Kaun khane se pehle meetha kha lega?',
  'Kaun Bigg Boss mein jaayega?',
  'Kaun apni saari salary khane pe uda dega?',
  'Kaun party mein apna phone kho dega?',
  'Kaun world record todega?',
  'Kaun gaana band hone ke baad bhi naachta rahega?',
  'Kaun Maggi banate hue kitchen mein aag laga dega?',
  'Kaun galti se viral ho jaayega?',
  'Kaun train mein anjaan bande se dosti kar lega?',
  'Kaun poora trip plan karke khud flight miss karega?',
  'Kaun teacher banega?',
  'Kaun GPS se bhi behes karega?',
  'Kaun shaadi mein sabse zyada naachega?',
  'Kaun rishtedaaron ke sawaalon se sabse pehle bhaagega?',
  'Kaun chai ke bina din shuru nahi kar sakta?',
  'Kaun "bhai ek minute" bolke ek ghanta lagata hai?',
  'Kaun cricket match ke liye sab kuch cancel kar dega?',
  'Kaun mushkil mein sabse pehle apni mummy ko phone karega?',
];
