/// The Hinglish confessions deck. Same spirit as the English one — nothing
/// that needs explaining, nothing that needs a drink — written the way a
/// room in Delhi or Mumbai would actually say it.
const kNeverHaveIEverPromptsHinglish = <String>[
  'Maine kabhi movie dekhte hue aansu nahi bahaye.',
  'Maine kabhi galat insaan ko text nahi bheja.',
  'Maine kabhi bimaar hone ka bahana banake kaam ya college bunk nahi kiya.',
  'Maine kabhi apne ex ka Instagram stalk nahi kiya.',
  'Maine kabhi bus ya metro mein sote hue apna stop miss nahi kiya.',
  'Maine kabhi apni umar ke baare mein jhooth nahi bola.',
  'Maine kabhi bekaar gift ko "bahut pasand aaya" nahi bola.',
  'Maine kabhi bathroom mein gaana nahi gaaya.',
  'Maine kabhi kisi ko ghost nahi kiya.',
  'Maine kabhi bheed ke saamne thokar khaake nahi gira.',
  'Maine kabhi kisi aur ka phone chupke se check nahi kiya.',
  'Maine kabhi apne aap se zor se baat nahi ki.',
  'Maine kabhi kisi se bachne ke liye fake phone call nahi ki.',
  'Maine kabhi mila hua gift kisi aur ko aage nahi diya.',
  'Maine kabhi train ya flight miss nahi ki.',
  'Maine kabhi dost ke partner pe crush nahi kiya.',
  'Maine kabhi anjaan gaane pe "yeh toh mera favourite hai" nahi bola.',
  'Maine kabhi shaadi mein bina bulaye khana nahi khaya.',
  'Maine kabhi chai mein biscuit dubo ke gira nahi diya.',
  'Maine kabhi auto wale se bhav taav mein haar nahi maani.',
  'Maine kabhi exam mein cheating nahi ki.',
  'Maine kabhi "padh raha hoon" bolke phone nahi chalaya.',
  'Maine kabhi pataakhe ki awaaz se darr ke chhalaang nahi maari.',
  'Maine kabhi shaadi mein dance floor pe akele nahi naacha.',
  'Maine kabhi kisi rishtedaar ka naam bhool ke "namaste uncle" nahi bola.',
  'Maine kabhi paani puri khaate hue aankhon se paani nahi nikala.',
  'Maine kabhi cricket match ke liye kaam se chhutti nahi li.',
  'Maine kabhi group chat mein galti se private message nahi bhej diya.',
  'Maine kabhi apni selfie 20 baar retake nahi ki.',
  'Maine kabhi late hone pe traffic ka bahana nahi banaya.',
  'Maine kabhi kisi ko "happy birthday" ek din late nahi bola.',
  'Maine kabhi bina ticket ke metro ya bus mein safar nahi kiya.',
];
