/// Bundled "Never have I ever..." prompts. Kept as plain Dart (not an asset
/// pack) — v1 has no pack selection, so there's nothing to justify the
/// asset-loading machinery the word-pack games use.
const kNeverHaveIEverPrompts = <String>[
  'Never have I ever cried during a movie.',
  "Never have I ever forgotten someone's name right after meeting them.",
  'Never have I ever sent a text to the wrong person.',
  'Never have I ever pretended to be sick to skip something.',
  'Never have I ever laughed so hard I cried.',
  'Never have I ever gotten lost in my own neighborhood.',
  'Never have I ever eaten food off the floor.',
  "Never have I ever stalked an ex's social media.",
  'Never have I ever fallen asleep in public.',
  'Never have I ever lied about my age.',
  'Never have I ever pretended to like a gift I hated.',
  'Never have I ever sung in the shower.',
  'Never have I ever ghosted someone.',
  'Never have I ever tripped in front of a crowd.',
  "Never have I ever snooped through someone's phone.",
  'Never have I ever skipped a whole day of work or school.',
  'Never have I ever talked to myself out loud.',
  'Never have I ever pretended to be on the phone to avoid someone.',
  'Never have I ever regifted a present.',
  'Never have I ever cried at a commercial.',
  'Never have I ever had a public breakup.',
  "Never have I ever liked an old photo while stalking someone's profile.",
  'Never have I ever eaten a meal meant for two people by myself.',
  'Never have I ever missed a flight or a train.',
  "Never have I ever had a crush on a friend's partner.",
  "Never have I ever pretended to know a song I'd never heard.",
  'Never have I ever walked into a glass door.',
  'Never have I ever googled myself.',
  'Never have I ever cheated on a test.',
  'Never have I ever cancelled plans just to stay home alone.',
  'Never have I ever had a wardrobe malfunction in public.',
  'Never have I ever lied to get out of a date.',
  'Never have I ever forgotten my own phone number.',
  'Never have I ever pretended to be someone else on a call.',
  'Never have I ever kept a library book way too long.',
  'Never have I ever laughed at the worst possible moment.',
  'Never have I ever shown up to an event on the wrong day.',
  'Never have I ever pretended to understand a joke I missed.',
  'Never have I ever gotten someone else in trouble to save myself.',
  'Never have I ever cried happy tears.',
];
